GET http://localhost:8080/cats?color=red
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJyb2xlcyI6WyJVU0VSIl0sIm93bmVySWQiOiIyN2M0N2ViMC1jZGEzLTQyYjItOGE2OS1kYzU5MzQzNDNiOTEifQ.d-zFFq9GPtYN86KsGdzuPBbh2sZA9YKRqs1QzIhmZgI