spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15433/cats
    username: cats
    password: cats
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: swagger-test.html
    enabled: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
server:
  port: 10010